[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "neoplasmes",email = "quiqqiqiu@gmail.com"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "xmlschema (>=3.4.5,<4.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "pydantic (>=2.0,<3.0)",
    "uvicorn[standard] (>=0.34.2,<0.35.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "websockets (>=15.0.1,<16.0.0)",
    "wsproto (>=1.2.0,<2.0.0)"
]


[project.scripts]
start = "main:start"

[tool.poetry]
packages = [
    { include = "core", from = "src" },
    { include = "app", from = "src" },
    { include = "env", from = "src" },
    { include = "api", from = "src" },
    { include = "shared", from = "src" },
    { include = "main.py", from = "src" },
]

[tool.uv]
exclude-newer = "2025-05-01T23:59:59Z"
python-downloads = "never"
python-preference = "only-system"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff==0.11.8",
    "pyright==1.1.400",
    "pytest==8.3.5",
]

[tool.ruff]
target-version = "py312"
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "B"]

[tool.ruff.lint.per-file-ignores]
"tests/test_backend.py" = ["E712"]
"src/core/entities/__init__.py" = ["I001"]
"src/core/processes/read_document_grammar/__init__.py" = ["I001"]
"src/app/use_cases/upload_documents/__init__.py" = ["I001"]
"src/api/http/schema/__init__.py" = ["I001"]

[tool.pyright]
include = ["src", "tests"]
exclude = [".venv", "dist", "build"]
pythonVersion = "3.12"
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"
extraPaths = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--import-mode=importlib --strict-config --strict-markers -ra"
filterwarnings = ["error"]
