[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "neoplasmes",email = "quiqqiqiu@gmail.com"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "xmlschema (>=3.4.5,<4.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "pydantic (>=2.0,<3.0)",
    "uvicorn[standard] (>=0.34.2,<0.35.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "websockets (>=15.0.1,<16.0.0)",
    "wsproto (>=1.2.0,<2.0.0)"
]


[project.optional-dependencies]
legacy-ml = [
    "transformers (>=4.51.2,<5.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "sentence-transformers (>=4.0.2,<5.0.0)",
]

[project.scripts]
start = "main:start"
infer-schema = "main:infer_schema_cli"
generate-schema = "main:generate_schema_cli"

[tool.poetry]
packages = [
    { include = "core", from = "src" },
    { include = "app", from = "src" },
    { include = "env", from = "src" },
    { include = "api", from = "src" },
    { include = "shared", from = "src" },
    { include = "main.py", from = "src" },
]

[tool.uv]
exclude-newer = "2025-05-01T23:59:59Z"
python-downloads = "never"
python-preference = "only-system"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "isort>=6.0.1,<7.0.0",
    "flake8>=7.2.0,<8.0.0",
    "flake8-quotes>=3.4.0,<4.0.0",
    "black>=25.1.0,<26.0.0",
]
